version: '3'

tasks:
  clean_up:
    desc: "Clean up all folders."
    dir: ../
    aliases:
      - clean
    cmds:
      - sudo rm -rf coverage/

  tests:
    desc: "Run tests and save coverage to coverage folder."
    dir: ../
    aliases:
      - test
    cmds:
      - mkdir -p ./coverage
      - |
        printf "integration={{.integration}}\n\n"  # View flag value
        if [ "{{.integration}}" == "true" ]; then
          go test -v -shuffle=on -coverprofile ./coverage/coverage.out -coverpkg=$(go list ./... | grep -v -F -f .coverignore | paste -sd, -) ./... -tags=integration
        else
          go test -v -shuffle=on -coverprofile ./coverage/coverage.out -coverpkg=$(go list ./... | grep -v -F -f .coverignore | paste -sd, -) ./...
        fi
      - go tool cover -html ./coverage/coverage.out -o ./coverage/coverage.html
    vars:
      integration:
        sh: echo "${integration:-false}"  # false by default

  benchmarks:
    desc: "Run benchmarks."
    dir: ../
    aliases:
      - bench
    cmd: go test -v . -bench=. -run=xxx -benchmem >> bench.txt

  linters:
    desc: "Run linters."
    dir: ../
    aliases:
      - lint
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
      - export PATH=$PATH:$(go env GOPATH)/bin
      - golangci-lint run -v --fix

